# Generated by Django 4.1.4 on 2022-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="PULA MEA", upload_to="media/"),
            preserve_default=False,
        ),
    ]
