# Generated by Django 4.1.4 on 2022-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0002_posttype_post_author_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.ManyToManyField(to="bucsani_school.posttype"),
        ),
    ]
