# Generated by Django 4.1.4 on 2022-12-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0005_postimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image",
            new_name="preview_image",
        ),
    ]
