# Generated by Django 4.1.4 on 2022-12-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0007_postfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="postfile",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="bucsani_school.post",
            ),
            preserve_default=False,
        ),
    ]
