# Generated by Django 4.1.4 on 2022-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bucsani_school",
            "0009_alter_galleryimage_image_alter_post_preview_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="documents")),
            ],
        ),
    ]
