# Generated by Django 4.1.4 on 2022-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0010_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("contact", models.TextField()),
            ],
        ),
    ]
