# Generated by Django 4.1.4 on 2023-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0012_siteconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Description",
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact",
            field=models.TextField(default="da"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="description",
            field=models.TextField(default="descriere"),
            preserve_default=False,
        ),
    ]
