# Generated by Django 4.1.4 on 2023-01-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0013_delete_description_siteconfig_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="preview_image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="background",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="contact",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
