# Generated by Django 4.1.4 on 2023-01-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "bucsani_school",
            "0014_alter_galleryimage_image_alter_post_preview_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="type",
        ),
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bucsani_school.posttype",
            ),
        ),
    ]
