# Generated by Django 4.1.4 on 2023-01-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0015_remove_post_type_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.FileField(upload_to="images"),
        ),
    ]
