# Generated by Django 4.1.4 on 2023-01-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bucsani_school", "0017_alter_post_preview_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="background",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
