# Generated by Django 4.1.6 on 2023-02-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucsani_school', '0020_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview_image',
        ),
    ]
